import type { DailyClosing } from "./types";

export const dailyClosings: DailyClosing[] = [
  {
    id: "dc-2026-07-26",
    entryNumber: "DC-2607-001",
    date: "2026-07-26",
    branch: { ar: "فرع الشفاء", en: "Ash Shifa Branch" },
    cashAccount: { ar: "الصندوق الرئيسي", en: "Main Cash Register" },
    openingBalance: 8400,
    notes: "تسليم الوردية للمحاسب بعد المراجعة.",
    status: "closed",
    closedBy: { ar: "خالد الزهراني", en: "Khalid Al-Zahrani" },
    closedAt: "2026-07-26T21:15:00+03:00",
    reviewedByAccountant: { ar: "نورة الدوسري", en: "Noura Al-Dosari" },
    reviewedAt: "2026-07-27T09:30:00+03:00",
    sales: [
      {
        id: "s1",
        referenceNumber: "TINV-2026-000001",
        description: { ar: "فاتورة صيانة — شركة الرياض للنقل", en: "Service invoice — Riyadh Transport Co." },
        amount: 621,
        paymentMethod: "bankTransfer",
        responsible: { ar: "نورة الدوسري", en: "Noura Al-Dosari" },
        source: "invoice",
        linkedInvoiceId: "inv-001",
        isManualAdjustment: false,
        time: "2026-07-26T16:05:00+03:00",
      },
    ],
    receipts: [
      {
        id: "r1",
        referenceNumber: "REC-2607-014",
        description: { ar: "تحصيل دفعة مقدّمة نقدًا — عميل فرد", en: "Cash advance collection — individual customer" },
        amount: 500,
        paymentMethod: "cash",
        responsible: { ar: "أحمد السالم", en: "Ahmed Al-Salem" },
        source: "manual",
        isManualAdjustment: true,
        time: "2026-07-26T10:20:00+03:00",
      },
    ],
    expenses: [
      {
        id: "e1",
        referenceNumber: "EXP-2607-009",
        description: { ar: "وقود مركبة الاستلام والتوصيل", en: "Fuel for pickup & delivery vehicle" },
        amount: 180,
        paymentMethod: "cash",
        responsible: { ar: "محمد الجهني", en: "Mohammed Al-Juhani" },
        source: "manual",
        isManualAdjustment: true,
        time: "2026-07-26T08:00:00+03:00",
      },
      {
        id: "e2",
        referenceNumber: "EXP-2607-010",
        description: { ar: "مستلزمات مكتبية", en: "Office supplies" },
        amount: 95,
        paymentMethod: "cash",
        responsible: { ar: "محمد الجهني", en: "Mohammed Al-Juhani" },
        source: "manual",
        isManualAdjustment: true,
        time: "2026-07-26T11:40:00+03:00",
      },
    ],
    purchases: [
      {
        id: "p1",
        referenceNumber: "PO-0726-004",
        description: { ar: "بطاريات 70 أمبير — شركة الخليج لقطع الغيار", en: "Battery 70A — Gulf Auto Parts Co." },
        amount: 2600,
        paymentMethod: "bankTransfer",
        responsible: { ar: "سلطان الحربي", en: "Sultan Al-Harbi" },
        source: "purchaseOrder",
        linkedPurchaseOrderId: "po-002",
        isManualAdjustment: false,
        time: "2026-07-26T13:00:00+03:00",
      },
    ],
    auditLog: [
      {
        id: "a1",
        timestamp: "2026-07-26T21:15:00+03:00",
        actor: { ar: "خالد الزهراني", en: "Khalid Al-Zahrani" },
        action: { ar: "تقفيل اليومية", en: "Daily closing locked" },
      },
      {
        id: "a2",
        timestamp: "2026-07-27T09:30:00+03:00",
        actor: { ar: "نورة الدوسري", en: "Noura Al-Dosari" },
        action: { ar: "مراجعة محاسبية واعتماد", en: "Accounting review approved" },
      },
      {
        id: "a3",
        timestamp: "2026-07-26T10:20:00+03:00",
        actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" },
        action: { ar: "إضافة سند قبض يدوي REC-2607-014", en: "Added manual receipt REC-2607-014" },
        note: { ar: "دفعة مقدمة غير مرتبطة بفاتورة صادرة بعد", en: "Advance not yet linked to an issued invoice" },
        isManualAdjustment: true,
      },
    ],
  },
  {
    id: "dc-2026-07-29",
    entryNumber: "DC-2607-002",
    date: "2026-07-29",
    branch: { ar: "فرع الشفاء", en: "Ash Shifa Branch" },
    cashAccount: { ar: "الصندوق الرئيسي", en: "Main Cash Register" },
    /** = الرصيد الختامي لتقفيل 2026-07-26 (8400 + (621+500) - (275+2600) = 6646). */
    openingBalance: 6646,
    status: "draft",
    sales: [],
    receipts: [
      {
        id: "r1",
        referenceNumber: "REC-2607-015",
        description: { ar: "دفعة نقدية من عميل بانتظار إصدار الفاتورة", en: "Cash payment from customer, invoice pending issue" },
        amount: 300,
        paymentMethod: "cash",
        responsible: { ar: "أحمد السالم", en: "Ahmed Al-Salem" },
        source: "manual",
        isManualAdjustment: true,
        time: "2026-07-29T09:15:00+03:00",
      },
    ],
    expenses: [
      {
        id: "e1",
        referenceNumber: "EXP-2607-011",
        description: { ar: "شاي وقهوة الاستراحة", en: "Break room tea and coffee" },
        amount: 45,
        paymentMethod: "cash",
        responsible: { ar: "محمد الجهني", en: "Mohammed Al-Juhani" },
        source: "manual",
        isManualAdjustment: true,
        time: "2026-07-29T07:45:00+03:00",
      },
    ],
    purchases: [],
    auditLog: [
      {
        id: "a1",
        timestamp: "2026-07-29T07:00:00+03:00",
        actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" },
        action: { ar: "فتح يومية جديدة", en: "New daily sheet opened" },
      },
      {
        id: "a2",
        timestamp: "2026-07-29T09:15:00+03:00",
        actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" },
        action: { ar: "إضافة سند قبض يدوي REC-2607-015", en: "Added manual receipt REC-2607-015" },
        isManualAdjustment: true,
      },
    ],
  },
];
