import type { Campaign } from "./types";

export const campaigns: Campaign[] = [
  {
    id: "cmp-001",
    name: { ar: "حملة صيانة الصيف", en: "Summer maintenance campaign" },
    channel: "sms",
    status: "active",
    targetSegment: { ar: "عملاء لم يزوروا منذ 6 أشهر", en: "Customers inactive for 6 months" },
    startDate: "2026-07-15",
    endDate: "2026-08-15",
    budget: 3000,
    reach: 1200,
  },
  {
    id: "cmp-002",
    name: { ar: "تذكير فحص التكييف", en: "AC check reminder" },
    channel: "email",
    status: "scheduled",
    targetSegment: { ar: "عملاء الأسطول", en: "Fleet customers" },
    startDate: "2026-08-01",
    endDate: "2026-08-10",
    budget: 800,
    reach: 0,
  },
  {
    id: "cmp-003",
    name: { ar: "عرض تبديل الإطارات", en: "Tire replacement promo" },
    channel: "social",
    status: "draft",
    targetSegment: { ar: "متابعو الصفحة", en: "Page followers" },
    startDate: "2026-08-05",
    endDate: "2026-08-20",
    budget: 1500,
    reach: 0,
  },
  {
    id: "cmp-004",
    name: { ar: "حملة الافتتاح السنوي", en: "Anniversary campaign" },
    channel: "print",
    status: "completed",
    targetSegment: { ar: "عملاء الحي المحيط", en: "Nearby neighborhood customers" },
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    budget: 2200,
    reach: 4300,
  },
  {
    id: "cmp-005",
    name: { ar: "برنامج ولاء العملاء", en: "Customer loyalty program" },
    channel: "sms",
    status: "paused",
    targetSegment: { ar: "عملاء متكررون", en: "Repeat customers" },
    startDate: "2026-05-01",
    endDate: "2026-12-31",
    budget: 5000,
    reach: 2100,
    notes: { ar: "أُوقفت مؤقتًا لمراجعة الميزانية", en: "Temporarily paused for budget review" },
  },
];
