import type { WorkOrder } from "./types";

export const workOrders: WorkOrder[] = [
  // استقبال (2)
  {
    id: "wo-001",
    number: "WO-0726-134",
    status: "reception",
    priority: "normal",
    customerId: "customer-001",
    vehicleId: "vehicle-001",
    mileageAtReception: 45200,
    complaint: { ar: "صوت من الفرامل الأمامية عند التباطؤ", en: "Noise from front brakes when slowing down" },
    technician: { ar: "سعيد ناصر", en: "Saeed Nasser" },
    bay: 3,
    receivedAt: "2026-07-28T07:30:00+03:00",
    estimatedDelivery: "2026-07-28T17:00:00+03:00",
    discount: 0,
    items: [],
    parts: [],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-28T07:30:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" }, note: { ar: "استُقبلت المركبة وتم إدخال بيانات العميل", en: "Vehicle received, customer details entered" } },
    ],
  },
  {
    id: "wo-002",
    number: "WO-0726-133",
    status: "reception",
    priority: "high",
    customerId: "customer-002",
    vehicleId: "vehicle-002",
    mileageAtReception: 128700,
    complaint: { ar: "تسريب زيت من المحرك وارتفاع في الحرارة", en: "Oil leak from engine and overheating" },
    technician: { ar: "ماجد العتيبي", en: "Majed Al-Otaibi" },
    bay: 7,
    receivedAt: "2026-07-28T08:15:00+03:00",
    estimatedDelivery: "2026-07-29T12:00:00+03:00",
    discount: 0,
    items: [],
    parts: [],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-28T08:15:00+03:00", actor: { ar: "محمد الجهني", en: "Mohammed Al-Juhani" }, note: { ar: "أُبلغ العميل بتحديد موعد الفحص خلال ساعة", en: "Customer informed of inspection within an hour" } },
    ],
  },
  // فحص (2)
  {
    id: "wo-003",
    number: "WO-0726-132",
    status: "inspection",
    priority: "normal",
    customerId: "customer-003",
    vehicleId: "vehicle-003",
    mileageAtReception: 188400,
    complaint: { ar: "قطع المكيف وضعف في الأداء العام", en: "AC not working and general performance issues" },
    technician: { ar: "ماجد العتيبي", en: "Majed Al-Otaibi" },
    bay: 1,
    receivedAt: "2026-07-28T06:45:00+03:00",
    estimatedDelivery: "2026-07-29T10:00:00+03:00",
    discount: 0,
    items: [
      { id: "i1", description: { ar: "فحص شامل للمكيف", en: "Full AC inspection" }, hours: 1, rate: 450, done: false },
      { id: "i2", description: { ar: "تشخيص منظومة الأداء", en: "Performance diagnostics" }, hours: 1.2, rate: 450, done: false },
    ],
    parts: [],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-28T06:45:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-28T07:10:00+03:00", actor: { ar: "ماجد العتيبي", en: "Majed Al-Otaibi" }, note: { ar: "بدأ الفحص الشامل", en: "Comprehensive inspection started" } },
    ],
  },
  {
    id: "wo-004",
    number: "WO-0726-131",
    status: "inspection",
    priority: "urgent",
    customerId: "customer-004",
    vehicleId: "vehicle-004",
    mileageAtReception: 32100,
    complaint: { ar: "ضوء تحقق المحرك مضيء وتردد في التسارع", en: "Check engine light on and hesitation on acceleration" },
    technician: { ar: "تركي الشمري", en: "Turki Al-Shammari" },
    bay: 5,
    receivedAt: "2026-07-28T07:00:00+03:00",
    estimatedDelivery: "2026-07-28T15:00:00+03:00",
    discount: 0,
    items: [
      { id: "i1", description: { ar: "قراءة كودات الأعطال OBD-II", en: "OBD-II fault code reading" }, hours: 0.5, rate: 450, done: false },
    ],
    parts: [],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-28T07:00:00+03:00", actor: { ar: "محمد الجهني", en: "Mohammed Al-Juhani" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-28T07:35:00+03:00", actor: { ar: "تركي الشمري", en: "Turki Al-Shammari" }, note: { ar: "حالة عاجلة — بدأ الفحص فورًا", en: "Urgent case — inspection started immediately" } },
    ],
  },
  // بانتظار الموافقة (3)
  {
    id: "wo-005",
    number: "WO-0726-130",
    status: "awaitingApproval",
    priority: "high",
    customerId: "customer-005",
    vehicleId: "vehicle-005",
    mileageAtReception: 61300,
    complaint: { ar: "صوت طقطقة من مقدمة السيارة عند الدوران", en: "Clicking sound from front when turning" },
    diagnosis: { ar: "تلف مفاصل الحركة الأمامية — تحتاج استبدال", en: "Damaged front CV joints — replacement required" },
    technician: { ar: "عبدالله الزهراني", en: "Abdullah Al-Zahrani" },
    receivedAt: "2026-07-27T10:30:00+03:00",
    estimatedDelivery: "2026-07-28T17:00:00+03:00",
    discount: 0,
    items: [
      { id: "i1", description: { ar: "استبدال مفصل حركة أيمن", en: "Right CV joint replacement" }, hours: 2, rate: 400, done: false },
    ],
    parts: [
      { id: "p1", name: { ar: "مفصل حركة أيمن — هيونداي سوناتا", en: "Right CV Joint — Hyundai Sonata" }, sku: "HYND-CVJ-R-21", qty: 1, unitPrice: 780, installStatus: "available" },
      { id: "p2", name: { ar: "غبار مفصل الحركة", en: "CV joint boot kit" }, sku: "HYND-CVJB-21", qty: 2, unitPrice: 280, installStatus: "available" },
    ],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-27T10:30:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-27T11:00:00+03:00", actor: { ar: "عبدالله الزهراني", en: "Abdullah Al-Zahrani" } },
      { id: "t3", status: "awaitingApproval", timestamp: "2026-07-27T13:15:00+03:00", actor: { ar: "عبدالله الزهراني", en: "Abdullah Al-Zahrani" }, note: { ar: "أُرسل التقدير للعميل", en: "Estimate sent to customer" } },
    ],
  },
  {
    id: "wo-006",
    number: "WO-0726-129",
    status: "awaitingApproval",
    priority: "normal",
    customerId: "customer-006",
    vehicleId: "vehicle-006",
    mileageAtReception: 95600,
    complaint: { ar: "تأخر في نقل الجير وصوت من ناحية الفتيس", en: "Delayed gear shifting and noise from gearbox area" },
    diagnosis: { ar: "تآكل في لوحة القابض وصرف زيت علبة التروس", en: "Clutch plate wear and gearbox oil flush needed" },
    technician: { ar: "ياسر الغامدي", en: "Yasser Al-Ghamdi" },
    receivedAt: "2026-07-27T13:00:00+03:00",
    estimatedDelivery: "2026-07-29T14:00:00+03:00",
    discount: 200,
    items: [
      { id: "i1", description: { ar: "استبدال لوحة القابض الكاملة", en: "Full clutch plate assembly replacement" }, hours: 3, rate: 400, done: false },
    ],
    parts: [
      { id: "p1", name: { ar: "مجموعة القابض الكاملة — فورد", en: "Full clutch kit — Ford Explorer" }, sku: "FORD-CLT-K-19", qty: 1, unitPrice: 1800, installStatus: "ordered" },
      { id: "p2", name: { ar: "زيت علبة تروس يدوية", en: "Manual gearbox oil" }, sku: "OIL-MTF-75W90", qty: 2, unitPrice: 150, installStatus: "available" },
    ],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-27T13:00:00+03:00", actor: { ar: "محمد الجهني", en: "Mohammed Al-Juhani" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-27T14:30:00+03:00", actor: { ar: "ياسر الغامدي", en: "Yasser Al-Ghamdi" } },
      { id: "t3", status: "awaitingApproval", timestamp: "2026-07-27T16:45:00+03:00", actor: { ar: "ياسر الغامدي", en: "Yasser Al-Ghamdi" }, note: { ar: "أُرسل التقدير — لم يرد العميل بعد", en: "Estimate sent — awaiting customer response" } },
    ],
  },
  {
    id: "wo-007",
    number: "WO-0726-116",
    status: "awaitingApproval",
    priority: "normal",
    customerId: "customer-007",
    vehicleId: "vehicle-007",
    mileageAtReception: 143800,
    complaint: { ar: "صيانة دورية + مشكلة في الزاوية الأمامية", en: "Periodic maintenance + front alignment issue" },
    diagnosis: { ar: "صيانة 150,000 كم شاملة + استبدال مساعدين أماميين", en: "150k km major service + front shock absorbers replacement" },
    technician: { ar: "سعيد ناصر", en: "Saeed Nasser" },
    receivedAt: "2026-07-27T09:00:00+03:00",
    estimatedDelivery: "2026-07-28T16:00:00+03:00",
    discount: 300,
    items: [
      { id: "i1", description: { ar: "صيانة 150,000 كم الكاملة", en: "150k km major service" }, hours: 3.5, rate: 400, done: false },
      { id: "i2", description: { ar: "استبدال مساعدين أماميين", en: "Front shock absorbers replacement" }, hours: 1, rate: 400, done: false },
    ],
    parts: [
      { id: "p1", name: { ar: "فلتر هواء — تويوتا هيلوكس", en: "Air filter — Toyota Hilux" }, sku: "TOY-AF-HLX20", qty: 1, unitPrice: 180, installStatus: "available" },
      { id: "p2", name: { ar: "فلتر زيت", en: "Oil filter" }, sku: "TOY-OF-HLX20", qty: 1, unitPrice: 65, installStatus: "available" },
      { id: "p3", name: { ar: "زيت محرك 10W-40", en: "Engine oil 10W-40" }, sku: "OIL-10W40-5L", qty: 2, unitPrice: 145, installStatus: "available" },
      { id: "p4", name: { ar: "مساعد أمامي أيمن", en: "Right front shock absorber" }, sku: "TOY-SHK-FR-HLX", qty: 1, unitPrice: 1100, installStatus: "ordered" },
      { id: "p5", name: { ar: "مساعد أمامي أيسر", en: "Left front shock absorber" }, sku: "TOY-SHK-FL-HLX", qty: 1, unitPrice: 1100, installStatus: "ordered" },
    ],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-27T09:00:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-27T09:30:00+03:00", actor: { ar: "سعيد ناصر", en: "Saeed Nasser" } },
      { id: "t3", status: "awaitingApproval", timestamp: "2026-07-27T11:00:00+03:00", actor: { ar: "سعيد ناصر", en: "Saeed Nasser" }, note: { ar: "أُرسل تقدير مفصّل — ينتظر موافقة مسؤول الشركة", en: "Detailed estimate sent — awaiting manager approval" } },
    ],
  },
  // تحت التنفيذ (4)
  {
    id: "wo-008",
    number: "WO-0726-128",
    status: "inProgress",
    priority: "high",
    customerId: "customer-008",
    vehicleId: "vehicle-008",
    mileageAtReception: 72400,
    complaint: { ar: "صيانة دورية + تعديل الفرامل الخلفية", en: "Periodic maintenance + rear brake adjustment" },
    diagnosis: { ar: "صيانة 75,000 كم + فرامل خلفية تحتاج تعديل", en: "75k km service + rear brakes need adjustment" },
    technician: { ar: "سعيد ناصر", en: "Saeed Nasser" },
    bay: 2,
    receivedAt: "2026-07-28T05:30:00+03:00",
    estimatedDelivery: "2026-07-28T14:00:00+03:00",
    discount: 0,
    items: [
      { id: "i1", description: { ar: "صيانة 75,000 كم الدورية", en: "75k km periodic service" }, hours: 2.5, rate: 500, done: true },
      { id: "i2", description: { ar: "تعديل الفرامل الخلفية وسحبها", en: "Rear brake adjustment and bleeding" }, hours: 1.5, rate: 500, done: false },
    ],
    parts: [
      { id: "p1", name: { ar: "زيت محرك 5W-30 ممتاز", en: "Premium engine oil 5W-30" }, sku: "OIL-5W30-PRE", qty: 2, unitPrice: 195, installStatus: "installed" },
      { id: "p2", name: { ar: "فلتر زيت — لاندكروزر", en: "Oil filter — Land Cruiser" }, sku: "TOY-OF-200", qty: 1, unitPrice: 95, installStatus: "installed" },
      { id: "p3", name: { ar: "فلتر هواء الكابينة", en: "Cabin air filter" }, sku: "TOY-CAF-200", qty: 1, unitPrice: 120, installStatus: "installed" },
      { id: "p4", name: { ar: "سائل فرامل DOT 4", en: "Brake fluid DOT 4" }, sku: "BRK-DOT4-500ML", qty: 2, unitPrice: 85, installStatus: "available" },
    ],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-28T05:30:00+03:00", actor: { ar: "محمد الجهني", en: "Mohammed Al-Juhani" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-28T06:00:00+03:00", actor: { ar: "سعيد ناصر", en: "Saeed Nasser" } },
      { id: "t3", status: "awaitingApproval", timestamp: "2026-07-28T06:30:00+03:00", actor: { ar: "سعيد ناصر", en: "Saeed Nasser" } },
      { id: "t4", status: "inProgress", timestamp: "2026-07-28T06:45:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" }, note: { ar: "وافق العميل هاتفيًا وبدأ العمل", en: "Customer approved via phone, work started" } },
    ],
  },
  {
    id: "wo-009",
    number: "WO-0726-125",
    status: "inProgress",
    priority: "normal",
    customerId: "customer-009",
    vehicleId: "vehicle-009",
    mileageAtReception: 109200,
    complaint: { ar: "مشكلة في نظام تعليق خلفي وميل عند الانعطاف", en: "Rear suspension problem and leaning when turning" },
    diagnosis: { ar: "استبدال مساعدين خلفيين + ضبط الزوايا", en: "Rear shock absorbers replacement + wheel alignment" },
    technician: { ar: "سعيد ناصر", en: "Saeed Nasser" },
    bay: 8,
    receivedAt: "2026-07-27T14:00:00+03:00",
    estimatedDelivery: "2026-07-28T16:00:00+03:00",
    discount: 0,
    items: [
      { id: "i1", description: { ar: "استبدال مساعدين خلفيين", en: "Rear shock absorbers replacement" }, hours: 2, rate: 400, done: true },
      { id: "i2", description: { ar: "ضبط زوايا العجلات الأربع", en: "4-wheel alignment" }, hours: 1, rate: 400, done: false },
    ],
    parts: [
      { id: "p1", name: { ar: "مساعد خلفي أيمن — نيسان باترول", en: "Right rear shock — Nissan Patrol" }, sku: "NIS-SHK-RR-PAT", qty: 1, unitPrice: 1400, installStatus: "installed" },
      { id: "p2", name: { ar: "مساعد خلفي أيسر — نيسان باترول", en: "Left rear shock — Nissan Patrol" }, sku: "NIS-SHK-RL-PAT", qty: 1, unitPrice: 1400, installStatus: "installed" },
    ],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-27T14:00:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-27T15:00:00+03:00", actor: { ar: "سعيد ناصر", en: "Saeed Nasser" } },
      { id: "t3", status: "awaitingApproval", timestamp: "2026-07-27T16:00:00+03:00", actor: { ar: "سعيد ناصر", en: "Saeed Nasser" } },
      { id: "t4", status: "inProgress", timestamp: "2026-07-28T07:00:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" }, note: { ar: "موافقة العميل مستلمة — بدأ الفريق الصباح", en: "Approval received — team started work in the morning" } },
    ],
  },
  {
    id: "wo-010",
    number: "WO-0726-122",
    status: "inProgress",
    priority: "urgent",
    customerId: "customer-010",
    vehicleId: "vehicle-010",
    mileageAtReception: 18400,
    complaint: { ar: "وقف المركبة فجأة وعدم الاستجابة — طوارئ", en: "Vehicle suddenly stalled and unresponsive — emergency" },
    diagnosis: { ar: "عطل في مضخة الوقود — استبدال فوري", en: "Fuel pump failure — immediate replacement needed" },
    technician: { ar: "تركي الشمري", en: "Turki Al-Shammari" },
    bay: 6,
    receivedAt: "2026-07-28T06:00:00+03:00",
    estimatedDelivery: "2026-07-28T13:00:00+03:00",
    discount: 0,
    items: [
      { id: "i1", description: { ar: "استبدال مضخة الوقود الداخلية", en: "Internal fuel pump replacement" }, hours: 3, rate: 400, done: false },
    ],
    parts: [
      { id: "p1", name: { ar: "مضخة وقود — فورد رينجر 2023", en: "Fuel pump — Ford Ranger 2023" }, sku: "FORD-FP-RNG23", qty: 1, unitPrice: 1650, installStatus: "available" },
      { id: "p2", name: { ar: "فلتر وقود", en: "Fuel filter" }, sku: "FORD-FF-RNG23", qty: 1, unitPrice: 200, installStatus: "available" },
    ],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-28T06:00:00+03:00", actor: { ar: "محمد الجهني", en: "Mohammed Al-Juhani" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-28T06:15:00+03:00", actor: { ar: "تركي الشمري", en: "Turki Al-Shammari" } },
      { id: "t3", status: "awaitingApproval", timestamp: "2026-07-28T06:30:00+03:00", actor: { ar: "تركي الشمري", en: "Turki Al-Shammari" } },
      { id: "t4", status: "inProgress", timestamp: "2026-07-28T06:40:00+03:00", actor: { ar: "محمد الجهني", en: "Mohammed Al-Juhani" }, note: { ar: "موافقة فورية — حالة طوارئ", en: "Immediate approval — emergency case" } },
    ],
  },
  {
    id: "wo-011",
    number: "WO-0726-118",
    status: "inProgress",
    priority: "normal",
    customerId: "customer-011",
    vehicleId: "vehicle-011",
    mileageAtReception: 341200,
    complaint: { ar: "صوت شديد من المحور الخلفي عند السرعات العالية", en: "Loud noise from rear axle at high speed" },
    diagnosis: { ar: "بيارينج المحور الخلفي تالفة — استبدال كامل", en: "Rear axle bearings damaged — complete replacement" },
    technician: { ar: "ماجد العتيبي", en: "Majed Al-Otaibi" },
    bay: 4,
    receivedAt: "2026-07-27T08:00:00+03:00",
    estimatedDelivery: "2026-07-28T18:00:00+03:00",
    discount: 500,
    items: [
      { id: "i1", description: { ar: "تفكيك وفحص المحور الخلفي", en: "Rear axle disassembly and inspection" }, hours: 3, rate: 400, done: true },
      { id: "i2", description: { ar: "استبدال بيارينج المحور", en: "Axle bearing replacement" }, hours: 4, rate: 400, done: false },
      { id: "i3", description: { ar: "ضبط الكراسة وإعادة التجميع", en: "Differential adjustment and reassembly" }, hours: 1.5, rate: 400, done: false },
    ],
    parts: [
      { id: "p1", name: { ar: "بيارينج محور خلفي — إيسوزو NPR", en: "Rear axle bearing — Isuzu NPR" }, sku: "ISZ-BRG-RA-NPR", qty: 2, unitPrice: 980, installStatus: "available" },
      { id: "p2", name: { ar: "طوق نفط المحور", en: "Axle oil seal" }, sku: "ISZ-SEAL-RA", qty: 2, unitPrice: 120, installStatus: "available" },
      { id: "p3", name: { ar: "زيت ديفرنشيل", en: "Differential oil" }, sku: "OIL-DIFF-SAE90", qty: 3, unitPrice: 100, installStatus: "available" },
    ],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-27T08:00:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-27T09:00:00+03:00", actor: { ar: "ماجد العتيبي", en: "Majed Al-Otaibi" } },
      { id: "t3", status: "awaitingApproval", timestamp: "2026-07-27T11:30:00+03:00", actor: { ar: "ماجد العتيبي", en: "Majed Al-Otaibi" } },
      { id: "t4", status: "inProgress", timestamp: "2026-07-27T13:00:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" }, note: { ar: "موافقة المؤسسة مستلمة — العمل جارٍ", en: "Company approval received — work in progress" } },
    ],
  },
  // بانتظار قطعة (2)
  {
    id: "wo-012",
    number: "WO-0726-117",
    status: "awaitingParts",
    priority: "high",
    customerId: "customer-011",
    vehicleId: "vehicle-012",
    mileageAtReception: 215400,
    complaint: { ar: "قطع المكيف تمامًا أثناء الطريق", en: "AC completely stopped working on the road" },
    diagnosis: { ar: "عطل في الكمبريسور — يحتاج استبدال عاجل", en: "Compressor failure — urgent replacement needed" },
    technician: { ar: "ماجد العتيبي", en: "Majed Al-Otaibi" },
    receivedAt: "2026-07-26T15:00:00+03:00",
    estimatedDelivery: "2026-07-29T12:00:00+03:00",
    discount: 0,
    items: [
      { id: "i1", description: { ar: "استبدال كمبريسور التكييف", en: "AC compressor replacement" }, hours: 4, rate: 400, done: false },
      { id: "i2", description: { ar: "شحن غاز التكييف", en: "AC gas recharge" }, hours: 0.5, rate: 400, done: false },
    ],
    parts: [
      { id: "p1", name: { ar: "كمبريسور مكيف — إيسوزو ELF", en: "AC compressor — Isuzu ELF" }, sku: "ISZ-COMP-AC-ELF", qty: 1, unitPrice: 7800, installStatus: "ordered" },
      { id: "p2", name: { ar: "غاز تكييف R-134a", en: "AC refrigerant R-134a" }, sku: "AC-R134A-1KG", qty: 1, unitPrice: 400, installStatus: "available" },
    ],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-26T15:00:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-26T16:00:00+03:00", actor: { ar: "ماجد العتيبي", en: "Majed Al-Otaibi" } },
      { id: "t3", status: "awaitingApproval", timestamp: "2026-07-26T17:00:00+03:00", actor: { ar: "ماجد العتيبي", en: "Majed Al-Otaibi" } },
      { id: "t4", status: "inProgress", timestamp: "2026-07-27T08:00:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t5", status: "awaitingParts", timestamp: "2026-07-27T09:00:00+03:00", actor: { ar: "ماجد العتيبي", en: "Majed Al-Otaibi" }, note: { ar: "الكمبريسور يُجلب من الرياض — وصول الثلاثاء", en: "Compressor sourced from Riyadh — expected arrival Tuesday" } },
    ],
  },
  {
    id: "wo-013",
    number: "WO-0726-110",
    status: "awaitingParts",
    priority: "normal",
    customerId: "customer-012",
    vehicleId: "vehicle-013",
    mileageAtReception: 78900,
    complaint: { ar: "تصادم خفيف وتلف في الرادياتير", en: "Minor collision and radiator damage" },
    diagnosis: { ar: "استبدال الرادياتير وفحص خط التبريد", en: "Radiator replacement and cooling system inspection" },
    technician: { ar: "عبدالله الزهراني", en: "Abdullah Al-Zahrani" },
    receivedAt: "2026-07-25T11:00:00+03:00",
    estimatedDelivery: "2026-07-29T17:00:00+03:00",
    discount: 0,
    items: [
      { id: "i1", description: { ar: "استبدال الرادياتير الكامل", en: "Full radiator replacement" }, hours: 2, rate: 400, done: false },
      { id: "i2", description: { ar: "فحص وتنظيف خطوط التبريد", en: "Cooling system flush and inspection" }, hours: 1, rate: 400, done: false },
    ],
    parts: [
      { id: "p1", name: { ar: "رادياتير — كيا سورينتو 2020", en: "Radiator — Kia Sorento 2020" }, sku: "KIA-RAD-SOR20", qty: 1, unitPrice: 2500, installStatus: "ordered" },
      { id: "p2", name: { ar: "سائل تبريد", en: "Coolant" }, sku: "COOL-G12-5L", qty: 2, unitPrice: 150, installStatus: "available" },
    ],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-25T11:00:00+03:00", actor: { ar: "محمد الجهني", en: "Mohammed Al-Juhani" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-25T12:00:00+03:00", actor: { ar: "عبدالله الزهراني", en: "Abdullah Al-Zahrani" } },
      { id: "t3", status: "awaitingApproval", timestamp: "2026-07-25T14:00:00+03:00", actor: { ar: "عبدالله الزهراني", en: "Abdullah Al-Zahrani" } },
      { id: "t4", status: "inProgress", timestamp: "2026-07-26T08:00:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t5", status: "awaitingParts", timestamp: "2026-07-26T09:30:00+03:00", actor: { ar: "عبدالله الزهراني", en: "Abdullah Al-Zahrani" }, note: { ar: "الرادياتير قيد الطلب — ٣-٤ أيام عمل", en: "Radiator ordered from supplier — 3-4 business days" } },
    ],
  },
  // جاهز للتسليم (2)
  {
    id: "wo-014",
    number: "WO-0726-115",
    status: "readyForDelivery",
    priority: "normal",
    customerId: "customer-010",
    vehicleId: "vehicle-019",
    mileageAtReception: 18400,
    complaint: { ar: "صيانة دورية 20,000 كم", en: "20k km periodic service" },
    diagnosis: { ar: "صيانة 20,000 كم مكتملة", en: "20k km service complete" },
    technician: { ar: "تركي الشمري", en: "Turki Al-Shammari" },
    receivedAt: "2026-07-27T07:00:00+03:00",
    estimatedDelivery: "2026-07-27T14:00:00+03:00",
    discount: 0,
    items: [
      { id: "i1", description: { ar: "صيانة 20,000 كم الدورية", en: "20k km service" }, hours: 2, rate: 400, done: true },
    ],
    parts: [
      { id: "p1", name: { ar: "زيت محرك 5W-20 فورد", en: "Ford engine oil 5W-20" }, sku: "FORD-OIL-5W20", qty: 1, unitPrice: 280, installStatus: "installed" },
      { id: "p2", name: { ar: "فلتر زيت — فورد رينجر", en: "Oil filter — Ford Ranger" }, sku: "FORD-OF-RNG", qty: 1, unitPrice: 120, installStatus: "installed" },
      { id: "p3", name: { ar: "فلتر هواء", en: "Air filter" }, sku: "FORD-AF-RNG", qty: 1, unitPrice: 180, installStatus: "installed" },
      { id: "p4", name: { ar: "ممسحة أمامية", en: "Front wiper blade" }, sku: "WIPER-FORD-F", qty: 2, unitPrice: 50, installStatus: "installed" },
    ],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-27T07:00:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-27T07:30:00+03:00", actor: { ar: "تركي الشمري", en: "Turki Al-Shammari" } },
      { id: "t3", status: "awaitingApproval", timestamp: "2026-07-27T08:00:00+03:00", actor: { ar: "تركي الشمري", en: "Turki Al-Shammari" } },
      { id: "t4", status: "inProgress", timestamp: "2026-07-27T08:15:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t5", status: "readyForDelivery", timestamp: "2026-07-27T11:30:00+03:00", actor: { ar: "تركي الشمري", en: "Turki Al-Shammari" }, note: { ar: "فحص الجودة اجتاز — جاهز للتسليم", en: "QC passed — ready for delivery" } },
    ],
  },
  {
    id: "wo-015",
    number: "WO-0726-113",
    status: "readyForDelivery",
    priority: "normal",
    customerId: "customer-003",
    vehicleId: "vehicle-020",
    mileageAtReception: 187900,
    complaint: { ar: "صيانة دورية 190,000 كم", en: "190k km service" },
    diagnosis: { ar: "صيانة مكتملة — زيت وفلاتر وفحص فرامل", en: "Service complete — oil, filters and brakes inspected" },
    technician: { ar: "ياسر الغامدي", en: "Yasser Al-Ghamdi" },
    receivedAt: "2026-07-27T09:00:00+03:00",
    estimatedDelivery: "2026-07-27T16:00:00+03:00",
    discount: 100,
    items: [
      { id: "i1", description: { ar: "صيانة 190,000 كم الشاملة", en: "190k km comprehensive service" }, hours: 3, rate: 400, done: true },
    ],
    parts: [
      { id: "p1", name: { ar: "زيت 5W-30", en: "Engine oil 5W-30" }, sku: "OIL-5W30-5L", qty: 2, unitPrice: 175, installStatus: "installed" },
      { id: "p2", name: { ar: "فلتر زيت — تاهو", en: "Oil filter — Tahoe" }, sku: "CHEV-OF-TAH", qty: 1, unitPrice: 110, installStatus: "installed" },
      { id: "p3", name: { ar: "شمع إشعال — مجموعة 8", en: "Spark plugs — set of 8" }, sku: "NGK-SP-GM-V8", qty: 1, unitPrice: 240, installStatus: "installed" },
    ],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-27T09:00:00+03:00", actor: { ar: "محمد الجهني", en: "Mohammed Al-Juhani" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-27T09:30:00+03:00", actor: { ar: "ياسر الغامدي", en: "Yasser Al-Ghamdi" } },
      { id: "t3", status: "awaitingApproval", timestamp: "2026-07-27T10:00:00+03:00", actor: { ar: "ياسر الغامدي", en: "Yasser Al-Ghamdi" } },
      { id: "t4", status: "inProgress", timestamp: "2026-07-27T10:15:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t5", status: "readyForDelivery", timestamp: "2026-07-27T13:45:00+03:00", actor: { ar: "ياسر الغامدي", en: "Yasser Al-Ghamdi" }, note: { ar: "فحص الجودة اجتاز — في انتظار العميل", en: "Passed QC — awaiting customer" } },
    ],
  },
  // مُسلَّم (5)
  {
    id: "wo-016",
    number: "WO-0726-108",
    status: "delivered",
    priority: "normal",
    customerId: "customer-013",
    vehicleId: "vehicle-014",
    mileageAtReception: 88400,
    complaint: { ar: "صيانة دورية 90,000 كم", en: "90k km service" },
    diagnosis: { ar: "صيانة مكتملة", en: "Service complete" },
    technician: { ar: "سعيد ناصر", en: "Saeed Nasser" },
    receivedAt: "2026-07-26T07:00:00+03:00",
    estimatedDelivery: "2026-07-26T14:00:00+03:00",
    deliveredAt: "2026-07-26T14:30:00+03:00",
    discount: 0,
    items: [{ id: "i1", description: { ar: "صيانة 90,000 كم", en: "90k km service" }, hours: 1.75, rate: 400, done: true }],
    parts: [
      { id: "p1", name: { ar: "زيت 0W-20", en: "Engine oil 0W-20" }, sku: "OIL-0W20-4L", qty: 1, unitPrice: 280, installStatus: "installed" },
      { id: "p2", name: { ar: "فلتر زيت — كورولا", en: "Oil filter — Corolla" }, sku: "TOY-OF-COR", qty: 1, unitPrice: 75, installStatus: "installed" },
      { id: "p3", name: { ar: "فلتر هواء — كورولا", en: "Air filter — Corolla" }, sku: "TOY-AF-COR", qty: 1, unitPrice: 125, installStatus: "installed" },
    ],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-26T07:00:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-26T07:30:00+03:00", actor: { ar: "سعيد ناصر", en: "Saeed Nasser" } },
      { id: "t3", status: "awaitingApproval", timestamp: "2026-07-26T08:00:00+03:00", actor: { ar: "سعيد ناصر", en: "Saeed Nasser" } },
      { id: "t4", status: "inProgress", timestamp: "2026-07-26T08:15:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t5", status: "readyForDelivery", timestamp: "2026-07-26T11:00:00+03:00", actor: { ar: "سعيد ناصر", en: "Saeed Nasser" } },
      { id: "t6", status: "delivered", timestamp: "2026-07-26T14:30:00+03:00", actor: { ar: "محمد الجهني", en: "Mohammed Al-Juhani" }, note: { ar: "تسلّم العميل مركبته بعد التوقيع", en: "Customer picked up vehicle after signing" } },
    ],
  },
  {
    id: "wo-017",
    number: "WO-0726-106",
    status: "delivered",
    priority: "high",
    customerId: "customer-014",
    vehicleId: "vehicle-015",
    mileageAtReception: 265800,
    complaint: { ar: "صرير من الداينمو عند التشغيل الساخن", en: "Squealing from alternator when engine hot" },
    diagnosis: { ar: "استبدال الداينمو وحزام التوقيت", en: "Alternator and drive belt replacement" },
    technician: { ar: "عبدالله الزهراني", en: "Abdullah Al-Zahrani" },
    receivedAt: "2026-07-25T10:00:00+03:00",
    estimatedDelivery: "2026-07-26T10:00:00+03:00",
    deliveredAt: "2026-07-26T09:30:00+03:00",
    discount: 0,
    items: [{ id: "i1", description: { ar: "استبدال الداينمو وحزام التوقيت", en: "Alternator and drive belt replacement" }, hours: 1.5, rate: 400, done: true }],
    parts: [
      { id: "p1", name: { ar: "داينمو — فولكسواجن كرافتر", en: "Alternator — VW Crafter" }, sku: "VW-ALT-CRFT19", qty: 1, unitPrice: 950, installStatus: "installed" },
      { id: "p2", name: { ar: "حزام توقيت", en: "Drive belt" }, sku: "VW-BELT-CRFT", qty: 1, unitPrice: 150, installStatus: "installed" },
    ],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-25T10:00:00+03:00", actor: { ar: "محمد الجهني", en: "Mohammed Al-Juhani" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-25T11:00:00+03:00", actor: { ar: "عبدالله الزهراني", en: "Abdullah Al-Zahrani" } },
      { id: "t3", status: "awaitingApproval", timestamp: "2026-07-25T12:00:00+03:00", actor: { ar: "عبدالله الزهراني", en: "Abdullah Al-Zahrani" } },
      { id: "t4", status: "inProgress", timestamp: "2026-07-26T07:00:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t5", status: "readyForDelivery", timestamp: "2026-07-26T08:30:00+03:00", actor: { ar: "عبدالله الزهراني", en: "Abdullah Al-Zahrani" } },
      { id: "t6", status: "delivered", timestamp: "2026-07-26T09:30:00+03:00", actor: { ar: "محمد الجهني", en: "Mohammed Al-Juhani" } },
    ],
  },
  {
    id: "wo-018",
    number: "WO-0726-102",
    status: "delivered",
    priority: "low",
    customerId: "customer-015",
    vehicleId: "vehicle-016",
    mileageAtReception: 54200,
    complaint: { ar: "تبديل إطارات وضبط زوايا", en: "Tire change and wheel alignment" },
    diagnosis: { ar: "تم التنفيذ", en: "Completed" },
    technician: { ar: "ياسر الغامدي", en: "Yasser Al-Ghamdi" },
    receivedAt: "2026-07-25T13:00:00+03:00",
    estimatedDelivery: "2026-07-25T15:30:00+03:00",
    deliveredAt: "2026-07-25T15:00:00+03:00",
    discount: 0,
    items: [
      { id: "i1", description: { ar: "تبديل إطارات (4 قطع) وضبط الزوايا", en: "Tire replacement (4 pcs) + alignment" }, hours: 1, rate: 400, done: true },
    ],
    parts: [
      { id: "p1", name: { ar: "إطار 185/65 R15 — يوكوهاما", en: "Tyre 185/65 R15 — Yokohama" }, sku: "YOK-185-65-R15", qty: 4, unitPrice: 400, installStatus: "installed" },
    ],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-25T13:00:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-25T13:15:00+03:00", actor: { ar: "ياسر الغامدي", en: "Yasser Al-Ghamdi" } },
      { id: "t3", status: "awaitingApproval", timestamp: "2026-07-25T13:20:00+03:00", actor: { ar: "ياسر الغامدي", en: "Yasser Al-Ghamdi" } },
      { id: "t4", status: "inProgress", timestamp: "2026-07-25T13:25:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t5", status: "readyForDelivery", timestamp: "2026-07-25T14:45:00+03:00", actor: { ar: "ياسر الغامدي", en: "Yasser Al-Ghamdi" } },
      { id: "t6", status: "delivered", timestamp: "2026-07-25T15:00:00+03:00", actor: { ar: "محمد الجهني", en: "Mohammed Al-Juhani" } },
    ],
  },
  {
    id: "wo-019",
    number: "WO-0726-099",
    status: "delivered",
    priority: "normal",
    customerId: "customer-016",
    vehicleId: "vehicle-017",
    mileageAtReception: 41600,
    complaint: { ar: "صيانة دورية وتحذير التعليق النشط", en: "Periodic service and active suspension warning" },
    diagnosis: { ar: "صيانة مكتملة وإعادة ضبط التعليق", en: "Service complete and suspension recalibrated" },
    technician: { ar: "تركي الشمري", en: "Turki Al-Shammari" },
    receivedAt: "2026-07-24T09:00:00+03:00",
    estimatedDelivery: "2026-07-24T17:00:00+03:00",
    deliveredAt: "2026-07-24T16:30:00+03:00",
    discount: 200,
    items: [
      { id: "i1", description: { ar: "صيانة دورية خاصة مرسيدس", en: "Mercedes periodic service" }, hours: 2, rate: 500, done: true },
      { id: "i2", description: { ar: "إعادة ضبط التعليق النشط", en: "Active suspension recalibration" }, hours: 1.5, rate: 500, done: true },
    ],
    parts: [
      { id: "p1", name: { ar: "زيت 0W-40 أصلي مرسيدس", en: "0W-40 genuine Mercedes oil" }, sku: "MB-OIL-0W40", qty: 1, unitPrice: 680, installStatus: "installed" },
      { id: "p2", name: { ar: "فلتر زيت C200", en: "C200 oil filter" }, sku: "MB-OF-C200", qty: 1, unitPrice: 280, installStatus: "installed" },
      { id: "p3", name: { ar: "فلتر هواء C200", en: "C200 air filter" }, sku: "MB-AF-C200", qty: 1, unitPrice: 320, installStatus: "installed" },
      { id: "p4", name: { ar: "شمع إشعال NGK — فصل 4", en: "NGK spark plugs — set of 4" }, sku: "NGK-SP-MB-I4", qty: 1, unitPrice: 400, installStatus: "installed" },
      { id: "p5", name: { ar: "فلتر كابينة C200", en: "C200 cabin filter" }, sku: "MB-CAF-C200", qty: 1, unitPrice: 320, installStatus: "installed" },
    ],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-24T09:00:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-24T09:30:00+03:00", actor: { ar: "تركي الشمري", en: "Turki Al-Shammari" } },
      { id: "t3", status: "awaitingApproval", timestamp: "2026-07-24T10:00:00+03:00", actor: { ar: "تركي الشمري", en: "Turki Al-Shammari" } },
      { id: "t4", status: "inProgress", timestamp: "2026-07-24T10:30:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t5", status: "readyForDelivery", timestamp: "2026-07-24T15:00:00+03:00", actor: { ar: "تركي الشمري", en: "Turki Al-Shammari" } },
      { id: "t6", status: "delivered", timestamp: "2026-07-24T16:30:00+03:00", actor: { ar: "محمد الجهني", en: "Mohammed Al-Juhani" } },
    ],
  },
  {
    id: "wo-020",
    number: "WO-0726-095",
    status: "delivered",
    priority: "low",
    customerId: "customer-017",
    vehicleId: "vehicle-018",
    mileageAtReception: 21100,
    complaint: { ar: "فحص ما قبل رحلة + تغيير زيت", en: "Pre-trip inspection + oil change" },
    diagnosis: { ar: "فحص مكتمل — المركبة بحالة ممتازة", en: "Inspection complete — vehicle in excellent condition" },
    technician: { ar: "ياسر الغامدي", en: "Yasser Al-Ghamdi" },
    receivedAt: "2026-07-24T11:00:00+03:00",
    estimatedDelivery: "2026-07-24T13:00:00+03:00",
    deliveredAt: "2026-07-24T12:45:00+03:00",
    discount: 0,
    items: [
      { id: "i1", description: { ar: "فحص ما قبل رحلة وتغيير الزيت", en: "Pre-trip inspection and oil change" }, hours: 0.75, rate: 400, done: true },
    ],
    parts: [
      { id: "p1", name: { ar: "زيت 5W-30 كيا", en: "Kia 5W-30 oil" }, sku: "KIA-OIL-5W30", qty: 1, unitPrice: 180, installStatus: "installed" },
      { id: "p2", name: { ar: "فلتر زيت — بيكانتو", en: "Oil filter — Picanto" }, sku: "KIA-OF-PIC", qty: 1, unitPrice: 60, installStatus: "installed" },
    ],
    timeline: [
      { id: "t1", status: "reception", timestamp: "2026-07-24T11:00:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t2", status: "inspection", timestamp: "2026-07-24T11:10:00+03:00", actor: { ar: "ياسر الغامدي", en: "Yasser Al-Ghamdi" } },
      { id: "t3", status: "awaitingApproval", timestamp: "2026-07-24T11:15:00+03:00", actor: { ar: "ياسر الغامدي", en: "Yasser Al-Ghamdi" } },
      { id: "t4", status: "inProgress", timestamp: "2026-07-24T11:20:00+03:00", actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" } },
      { id: "t5", status: "readyForDelivery", timestamp: "2026-07-24T12:30:00+03:00", actor: { ar: "ياسر الغامدي", en: "Yasser Al-Ghamdi" } },
      { id: "t6", status: "delivered", timestamp: "2026-07-24T12:45:00+03:00", actor: { ar: "محمد الجهني", en: "Mohammed Al-Juhani" } },
    ],
  },
];

export function getWorkOrderById(id: string): WorkOrder | undefined {
  return workOrders.find((wo) => wo.id === id);
}

export function getWorkOrderStats() {
  const open = workOrders.filter((wo) => wo.status !== "delivered").length;
  const awaitingApproval = workOrders.filter((wo) => wo.status === "awaitingApproval").length;
  const inProgress = workOrders.filter((wo) => wo.status === "inProgress").length;
  const readyForDelivery = workOrders.filter((wo) => wo.status === "readyForDelivery").length;
  return { open, awaitingApproval, inProgress, readyForDelivery };
}
