import type { Address, Customer } from "@/lib/domain/contracts";

function riyadhAddress(district: { ar: string; en: string }, street: { ar: string; en: string }, buildingNo: string, postalCode: string): Address {
  return {
    buildingNo,
    street,
    district,
    city: { ar: "الرياض", en: "Riyadh" },
    postalCode,
    country: { ar: "المملكة العربية السعودية", en: "Kingdom of Saudi Arabia" },
  };
}

export const customers: Customer[] = [
  {
    id: "customer-001",
    kind: "individual",
    displayName: { ar: "راشد البلوي", en: "Rashed Al-Balawi" },
    phone: "+966501234501",
    email: "rashed.balawi@example.com",
    nationalAddress: riyadhAddress({ ar: "حي العليا", en: "Al Olaya Dist." }, { ar: "شارع التخصصي", en: "Tahlia St." }, "3311", "12222"),
  },
  {
    id: "customer-002",
    kind: "company",
    displayName: { ar: "شركة الرياض للنقل", en: "Riyadh Transport Co." },
    legalName: { ar: "شركة الرياض للنقل المحدودة", en: "Riyadh Transport Co. Ltd." },
    phone: "+966114455201",
    email: "billing@riyadh-transport.sa",
    vatNumber: "310112233400003",
    commercialRegistration: "1010098765",
    nationalAddress: riyadhAddress({ ar: "حي الصناعية", en: "Industrial Dist." }, { ar: "شارع الأمير سلطان", en: "Prince Sultan St." }, "7712", "13212"),
  },
  {
    id: "customer-003",
    kind: "individual",
    displayName: { ar: "سلطان العنزي", en: "Sultan Al-Anazi" },
    phone: "+966501234503",
    email: "sultan.anazi@example.com",
    nationalAddress: riyadhAddress({ ar: "حي النرجس", en: "Al Narjis Dist." }, { ar: "شارع الأمير محمد بن سلمان", en: "Prince Mohammed bin Salman Rd." }, "5521", "13512"),
  },
  {
    id: "customer-004",
    kind: "individual",
    displayName: { ar: "فاطمة الغامدي", en: "Fatimah Al-Ghamdi" },
    phone: "+966501234504",
    email: "fatimah.ghamdi@example.com",
    nationalAddress: riyadhAddress({ ar: "حي الملقا", en: "Al Malqa Dist." }, { ar: "طريق الملك عبدالله", en: "King Abdullah Rd." }, "8834", "13521"),
  },
  {
    id: "customer-005",
    kind: "individual",
    displayName: { ar: "نورة القحطاني", en: "Noura Al-Qahtani" },
    phone: "+966501234505",
    email: "noura.qahtani@example.com",
    nationalAddress: riyadhAddress({ ar: "حي الياسمين", en: "Al Yasmin Dist." }, { ar: "شارع أنس بن مالك", en: "Anas bin Malik St." }, "1298", "13326"),
  },
  {
    id: "customer-006",
    kind: "individual",
    displayName: { ar: "بدر الشهري", en: "Badr Al-Shehri" },
    phone: "+966501234506",
    email: "badr.shehri@example.com",
    nationalAddress: riyadhAddress({ ar: "حي الروضة", en: "Al Rawdah Dist." }, { ar: "شارع الأمير تركي", en: "Prince Turki St." }, "4456", "12831"),
  },
  {
    id: "customer-007",
    kind: "company",
    displayName: { ar: "مؤسسة التميمي للمقاولات", en: "Al-Tamimi Contracting Est." },
    legalName: { ar: "مؤسسة التميمي للمقاولات العامة", en: "Al-Tamimi General Contracting Est." },
    phone: "+966114455207",
    email: "accounts@tamimi-cont.sa",
    vatNumber: "310223344500003",
    commercialRegistration: "1010087654",
    nationalAddress: riyadhAddress({ ar: "حي السلي", en: "As Sulay Dist." }, { ar: "طريق الخرج", en: "Al Kharj Rd." }, "2290", "14212"),
  },
  {
    id: "customer-008",
    kind: "individual",
    displayName: { ar: "خالد الحربي", en: "Khalid Al-Harbi" },
    phone: "+966501234508",
    email: "khalid.harbi@example.com",
    nationalAddress: riyadhAddress({ ar: "حي الشفا", en: "Ash Shifa Dist." }, { ar: "شارع الأمير سعد بن عبدالرحمن", en: "Prince Saad bin Abdulrahman St." }, "6673", "13312"),
  },
  {
    id: "customer-009",
    kind: "individual",
    displayName: { ar: "فهد الدوسري", en: "Fahd Al-Dosari" },
    phone: "+966501234509",
    email: "fahd.dosari@example.com",
    nationalAddress: riyadhAddress({ ar: "حي المونسية", en: "Al Munsiyah Dist." }, { ar: "شارع عثمان بن عفان", en: "Othman bin Affan St." }, "9012", "13246"),
  },
  {
    id: "customer-010",
    kind: "company",
    displayName: { ar: "شركة نماء التجارية", en: "Namaa Trading Co." },
    legalName: { ar: "شركة نماء التجارية المحدودة", en: "Namaa Trading Co. Ltd." },
    phone: "+966114455210",
    email: "finance@namaa-trading.sa",
    vatNumber: "310334455600003",
    commercialRegistration: "1010076543",
    nationalAddress: riyadhAddress({ ar: "حي العزيزية", en: "Al Aziziyah Dist." }, { ar: "طريق الدمام", en: "Dammam Rd." }, "3341", "14612"),
  },
  {
    id: "customer-011",
    kind: "company",
    displayName: { ar: "مؤسسة الرواد للنقل", en: "Al-Ruwad Transport Est." },
    legalName: { ar: "مؤسسة الرواد للنقل البري", en: "Al-Ruwad Land Transport Est." },
    phone: "+966114455211",
    email: "ops@ruwad-transport.sa",
    vatNumber: "310445566700003",
    commercialRegistration: "1010065432",
    nationalAddress: riyadhAddress({ ar: "حي الصناعية الثانية", en: "Second Industrial Dist." }, { ar: "شارع صناعية", en: "Industrial St." }, "1156", "13425"),
  },
  {
    id: "customer-012",
    kind: "individual",
    displayName: { ar: "وليد الخثلان", en: "Walid Al-Khutlan" },
    phone: "+966501234512",
    email: "walid.khutlan@example.com",
    nationalAddress: riyadhAddress({ ar: "حي الورود", en: "Al Wurud Dist." }, { ar: "شارع الستين", en: "Sittin St." }, "7789", "12241"),
  },
  {
    id: "customer-013",
    kind: "individual",
    displayName: { ar: "محمد الزيد", en: "Mohammed Al-Zayd" },
    phone: "+966501234513",
    email: "mohammed.zayd@example.com",
    nationalAddress: riyadhAddress({ ar: "حي قرطبة", en: "Qurtubah Dist." }, { ar: "شارع الإمام سعود", en: "Imam Saud St." }, "2231", "13244"),
  },
  {
    id: "customer-014",
    kind: "company",
    displayName: { ar: "شركة الخليج للمقاولات", en: "Gulf Contracting Co." },
    legalName: { ar: "شركة الخليج للمقاولات العامة المحدودة", en: "Gulf General Contracting Co. Ltd." },
    phone: "+966114455214",
    email: "ap@gulf-contracting.sa",
    vatNumber: "310556677800003",
    commercialRegistration: "1010054321",
    nationalAddress: riyadhAddress({ ar: "حي الملز", en: "Al Malaz Dist." }, { ar: "شارع الأمير عبدالعزيز بن مساعد", en: "Prince Abdulaziz bin Musaid St." }, "4467", "11439"),
  },
  {
    id: "customer-015",
    kind: "individual",
    displayName: { ar: "سلوى الحربي", en: "Salwa Al-Harbi" },
    phone: "+966501234515",
    email: "salwa.harbi@example.com",
    nationalAddress: riyadhAddress({ ar: "حي الربوة", en: "Ar Rabwah Dist." }, { ar: "شارع خالد بن الوليد", en: "Khalid bin Al Walid St." }, "5523", "11421"),
  },
  {
    id: "customer-016",
    kind: "individual",
    displayName: { ar: "طلال العسيري", en: "Talal Al-Asiri" },
    phone: "+966501234516",
    email: "talal.asiri@example.com",
    nationalAddress: riyadhAddress({ ar: "حي الحمراء", en: "Al Hamra Dist." }, { ar: "شارع الأمير فيصل بن تركي", en: "Prince Faisal bin Turki St." }, "8845", "12613"),
  },
  {
    id: "customer-017",
    kind: "individual",
    displayName: { ar: "حسن الزهراني", en: "Hassan Al-Zahrani" },
    phone: "+966501234517",
    email: "hassan.zahrani@example.com",
    nationalAddress: riyadhAddress({ ar: "حي الديرة", en: "Ad Dirah Dist." }, { ar: "شارع الإمام تركي بن عبدالله", en: "Imam Turki bin Abdullah St." }, "1102", "11411"),
  },
];
