import { buildBuyerSnapshot, buildSellerSnapshot } from "@/lib/services/invoice-service";
import { customers } from "@/modules/customers/data";
import type { Customer } from "@/lib/domain/contracts";
import type { Invoice } from "./types";

const customersById = new Map<string, Customer>(customers.map((customer) => [customer.id, customer]));

function buyer(customerId: string) {
  const customer = customersById.get(customerId);
  if (!customer) throw new Error(`Unknown mock customer ${customerId}`);
  return buildBuyerSnapshot(customer);
}

const seller = buildSellerSnapshot();

export const invoices: Invoice[] = [
  {
    id: "inv-001",
    documentType: "invoice",
    kind: "standard",
    number: "TINV-2026-000001",
    sequenceNumber: 1,
    uuid: "3f1a9c2e-4b7d-4e11-9a2f-6c8d0e1a2b01",
    status: "paid",
    issuedAt: "2026-07-26T16:05:00+03:00",
    supplyDate: "2026-07-26",
    customerId: "customer-002",
    vehicleId: "vehicle-002",
    linkedWorkOrderId: "wo-002",
    sellerSnapshot: seller,
    buyerSnapshot: buyer("customer-002"),
    paymentMethod: "bankTransfer",
    paidAmount: 621,
    items: [
      {
        id: "i1",
        description: { ar: "إصلاح تسريب زيت المحرك", en: "Engine oil leak repair" },
        qty: 1,
        unitPrice: 400,
        discount: 0,
        taxCategory: "standard",
        taxRate: 0.15,
      },
      {
        id: "i2",
        description: { ar: "أجرة فحص وتشخيص", en: "Diagnostic labor" },
        qty: 1,
        unitPrice: 140,
        discount: 0,
        taxCategory: "standard",
        taxRate: 0.15,
      },
    ],
    auditLog: [
      {
        id: "a1",
        timestamp: "2026-07-26T16:05:00+03:00",
        actor: { ar: "نورة الدوسري", en: "Noura Al-Dosari" },
        action: { ar: "إصدار الفاتورة", en: "Invoice issued" },
      },
      {
        id: "a2",
        timestamp: "2026-07-27T09:00:00+03:00",
        actor: { ar: "نورة الدوسري", en: "Noura Al-Dosari" },
        action: { ar: "تسجيل سداد كامل عبر تحويل بنكي", en: "Full payment recorded via bank transfer" },
      },
    ],
  },
  {
    id: "inv-002",
    documentType: "invoice",
    kind: "simplified",
    number: "SINV-2026-000001",
    sequenceNumber: 1,
    uuid: "7b2e4d5f-8c1a-4f22-b3d4-1e9f0a2b3c02",
    status: "issued",
    issuedAt: "2026-07-28T12:00:00+03:00",
    supplyDate: "2026-07-28",
    dueAt: "2026-08-04T12:00:00+03:00",
    customerId: "customer-001",
    vehicleId: "vehicle-001",
    linkedWorkOrderId: "wo-001",
    sellerSnapshot: seller,
    buyerSnapshot: buyer("customer-001"),
    paymentMethod: "cash",
    paidAmount: 0,
    items: [
      {
        id: "i1",
        description: { ar: "استبدال طقم فحمات فرامل أمامية", en: "Front brake pad set replacement" },
        qty: 1,
        unitPrice: 320,
        discount: 0,
        taxCategory: "standard",
        taxRate: 0.15,
      },
      {
        id: "i2",
        description: { ar: "أجرة عمل", en: "Labor" },
        qty: 1,
        unitPrice: 100,
        discount: 20,
        taxCategory: "standard",
        taxRate: 0.15,
      },
    ],
    auditLog: [
      {
        id: "a1",
        timestamp: "2026-07-28T12:00:00+03:00",
        actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" },
        action: { ar: "إصدار الفاتورة", en: "Invoice issued" },
      },
    ],
  },
  {
    id: "inv-003",
    documentType: "invoice",
    kind: "standard",
    number: "TINV-2026-000002",
    sequenceNumber: 2,
    uuid: "1c3d5e7f-9a0b-4c33-8e2f-2a4b6c8d0e03",
    status: "issued",
    issuedAt: "2026-07-22T14:00:00+03:00",
    supplyDate: "2026-07-22",
    customerId: "customer-011",
    vehicleId: "vehicle-011",
    sellerSnapshot: seller,
    buyerSnapshot: buyer("customer-011"),
    paymentMethod: "credit",
    paidAmount: 0,
    items: [
      {
        id: "i1",
        description: { ar: "صيانة دورية أسطول (٣ مركبات)", en: "Fleet routine maintenance (3 vehicles)" },
        qty: 3,
        unitPrice: 220,
        discount: 0,
        taxCategory: "standard",
        taxRate: 0.15,
      },
      {
        id: "i2",
        description: { ar: "نقل مركبات بين المواقع — خدمة معفاة من الضريبة", en: "Inter-site vehicle transport — VAT-exempt service" },
        qty: 1,
        unitPrice: 150,
        discount: 0,
        taxCategory: "exempt",
        taxRate: 0,
        exemptionReason: { ar: "خدمة نقل معفاة بموجب المادة (33) من نظام ضريبة القيمة المضافة", en: "Transport service exempt under VAT Law Article (33)" },
      },
    ],
    auditLog: [
      {
        id: "a1",
        timestamp: "2026-07-22T14:00:00+03:00",
        actor: { ar: "نورة الدوسري", en: "Noura Al-Dosari" },
        action: { ar: "إصدار الفاتورة", en: "Invoice issued" },
      },
    ],
  },
  {
    id: "inv-004",
    documentType: "creditNote",
    kind: "standard",
    number: "CN-2026-000001",
    sequenceNumber: 1,
    uuid: "9d0e1f2a-3b4c-4d55-9f6a-4c6e8f0a2b04",
    status: "issued",
    issuedAt: "2026-07-27T10:00:00+03:00",
    supplyDate: "2026-07-27",
    customerId: "customer-002",
    sellerSnapshot: seller,
    buyerSnapshot: buyer("customer-002"),
    paymentMethod: "bankTransfer",
    paidAmount: 0,
    relatedInvoiceId: "inv-001",
    reasonForNote: { ar: "تصحيح خطأ في سعر بند أجرة الفحص — تم تخفيضه بعد مراجعة العميل", en: "Correction of diagnostic labor price after customer review" },
    items: [
      {
        id: "i1",
        description: { ar: "تسوية سعر أجرة فحص وتشخيص", en: "Diagnostic labor price adjustment" },
        qty: 1,
        unitPrice: 40,
        discount: 0,
        taxCategory: "standard",
        taxRate: 0.15,
      },
    ],
    auditLog: [
      {
        id: "a1",
        timestamp: "2026-07-27T10:00:00+03:00",
        actor: { ar: "نورة الدوسري", en: "Noura Al-Dosari" },
        action: { ar: "إصدار إشعار دائن مرتبط بالفاتورة TINV-2026-000001", en: "Credit note issued against invoice TINV-2026-000001" },
        note: { ar: "تسوية يدوية بعد مراجعة محاسبية", en: "Manual adjustment after accounting review" },
        isManualAdjustment: true,
      },
    ],
  },
  {
    id: "inv-005",
    documentType: "invoice",
    kind: "simplified",
    number: "SINV-2026-000002",
    sequenceNumber: 2,
    uuid: "5e6f7a8b-9c0d-4e66-8a1b-6d8f0a2c4e05",
    status: "draft",
    supplyDate: "2026-07-29",
    customerId: "customer-006",
    sellerSnapshot: seller,
    buyerSnapshot: buyer("customer-006"),
    paymentMethod: "card",
    paidAmount: 0,
    items: [
      {
        id: "i1",
        description: { ar: "تبديل زيت وفلتر", en: "Oil and filter change" },
        qty: 1,
        unitPrice: 180,
        discount: 0,
        taxCategory: "standard",
        taxRate: 0.15,
      },
    ],
    auditLog: [
      {
        id: "a1",
        timestamp: "2026-07-29T08:10:00+03:00",
        actor: { ar: "أحمد السالم", en: "Ahmed Al-Salem" },
        action: { ar: "إنشاء مسودة فاتورة", en: "Draft invoice created" },
      },
    ],
  },
  {
    id: "inv-006",
    documentType: "invoice",
    kind: "standard",
    number: "TINV-2026-000003",
    sequenceNumber: 3,
    uuid: "2a4b6c8d-0e1f-4a77-9b2c-8e0a2c4e6f06",
    status: "overdue",
    issuedAt: "2026-07-05T09:00:00+03:00",
    supplyDate: "2026-07-05",
    dueAt: "2026-07-12T09:00:00+03:00",
    customerId: "customer-014",
    sellerSnapshot: seller,
    buyerSnapshot: buyer("customer-014"),
    paymentMethod: "credit",
    paidAmount: 0,
    items: [
      {
        id: "i1",
        description: { ar: "قطع غيار مستوردة — معدل ضريبة صفري (تصدير مؤقت)", en: "Imported parts — zero-rated (temporary export)" },
        qty: 1,
        unitPrice: 1200,
        discount: 0,
        taxCategory: "zeroRated",
        taxRate: 0,
        exemptionReason: { ar: "توريد صفري النسبة بموجب لائحة التصدير المؤقت", en: "Zero-rated supply under temporary export regulations" },
      },
    ],
    auditLog: [
      {
        id: "a1",
        timestamp: "2026-07-05T09:00:00+03:00",
        actor: { ar: "نورة الدوسري", en: "Noura Al-Dosari" },
        action: { ar: "إصدار الفاتورة", en: "Invoice issued" },
      },
    ],
  },
];
