import type { Vehicle } from "@/lib/domain/contracts";

export const vehicles: Vehicle[] = [
  { id: "vehicle-001", customerId: "customer-001", make: { ar: "تويوتا", en: "Toyota" }, model: { ar: "كامري", en: "Camry" }, year: 2023, plate: "أ ب ج 1234", vin: "JTDBE40K993100001", color: { ar: "أبيض لؤلؤي", en: "Pearl White" }, fuelType: "gasoline", status: "active", mileage: 45200 },
  { id: "vehicle-002", customerId: "customer-002", make: { ar: "ميتسوبيشي", en: "Mitsubishi" }, model: { ar: "كانتر", en: "Canter" }, year: 2021, plate: "ه و ز 5678", color: { ar: "أبيض", en: "White" }, fuelType: "diesel", status: "active", mileage: 128700 },
  { id: "vehicle-003", customerId: "customer-003", make: { ar: "شفروليه", en: "Chevrolet" }, model: { ar: "تاهو", en: "Tahoe" }, year: 2018, plate: "ط ص ق 5620", vin: "1GNSKBKC7JR344782", color: { ar: "أسود", en: "Black" }, fuelType: "gasoline", status: "active", mileage: 188400 },
  { id: "vehicle-004", customerId: "customer-004", make: { ar: "هوندا", en: "Honda" }, model: { ar: "أكورد", en: "Accord" }, year: 2022, plate: "ي ك ل 9012", color: { ar: "فضي", en: "Silver" }, fuelType: "gasoline", status: "active", mileage: 31500 },
  { id: "vehicle-005", customerId: "customer-005", make: { ar: "هيونداي", en: "Hyundai" }, model: { ar: "سوناتا", en: "Sonata" }, year: 2021, plate: "س ع ن 1182", vin: "KMHE251BBMA000052", color: { ar: "رمادي", en: "Gray" }, fuelType: "gasoline", status: "active", mileage: 62300 },
  { id: "vehicle-006", customerId: "customer-006", make: { ar: "فورد", en: "Ford" }, model: { ar: "إكسبلورر", en: "Explorer" }, year: 2019, plate: "م ن س 3344", color: { ar: "أزرق", en: "Blue" }, fuelType: "gasoline", status: "active", mileage: 94800 },
  { id: "vehicle-007", customerId: "customer-007", make: { ar: "تويوتا", en: "Toyota" }, model: { ar: "هيلوكس", en: "Hilux" }, year: 2020, plate: "ع ف ق 7788", vin: "MR0EX32G5L4032891", color: { ar: "أبيض", en: "White" }, fuelType: "diesel", status: "active", mileage: 142100 },
  { id: "vehicle-008", customerId: "customer-008", make: { ar: "تويوتا", en: "Toyota" }, model: { ar: "لاندكروزر", en: "Land Cruiser" }, year: 2022, plate: "ب ج د 4271", vin: "JTMHV05J904134101", color: { ar: "أسود", en: "Black" }, fuelType: "gasoline", status: "active", mileage: 38900 },
  { id: "vehicle-009", customerId: "customer-009", make: { ar: "نيسان", en: "Nissan" }, model: { ar: "باترول", en: "Patrol" }, year: 2020, plate: "د ك م 7756", color: { ar: "بني", en: "Brown" }, fuelType: "gasoline", status: "active", mileage: 87600 },
  { id: "vehicle-010", customerId: "customer-010", make: { ar: "فورد", en: "Ford" }, model: { ar: "رينجر", en: "Ranger" }, year: 2023, plate: "ح ل ب 3309", color: { ar: "أحمر", en: "Red" }, fuelType: "diesel", status: "active", mileage: 18400 },
  { id: "vehicle-011", customerId: "customer-011", make: { ar: "إيسوزو", en: "Isuzu" }, model: { ar: "NPR", en: "NPR" }, year: 2019, plate: "أ ه ر 9034", color: { ar: "أبيض", en: "White" }, fuelType: "diesel", status: "active", mileage: 165200 },
  { id: "vehicle-012", customerId: "customer-011", make: { ar: "إيسوزو", en: "Isuzu" }, model: { ar: "ELF", en: "ELF" }, year: 2020, plate: "ب ر ت 2200", color: { ar: "أبيض", en: "White" }, fuelType: "diesel", status: "active", mileage: 121300 },
  { id: "vehicle-013", customerId: "customer-012", make: { ar: "كيا", en: "Kia" }, model: { ar: "سورينتو", en: "Sorento" }, year: 2020, plate: "ر ز س 2211", color: { ar: "فضي", en: "Silver" }, fuelType: "gasoline", status: "active", mileage: 76500 },
  { id: "vehicle-014", customerId: "customer-013", make: { ar: "تويوتا", en: "Toyota" }, model: { ar: "كورولا", en: "Corolla" }, year: 2021, plate: "أ ب ت 1122", color: { ar: "أبيض", en: "White" }, fuelType: "hybrid", status: "active", mileage: 54200 },
  { id: "vehicle-015", customerId: "customer-014", make: { ar: "فولكسواجن", en: "Volkswagen" }, model: { ar: "كرافتر", en: "Crafter" }, year: 2019, plate: "ث ج ح 4455", color: { ar: "أبيض", en: "White" }, fuelType: "diesel", status: "active", mileage: 158900 },
  { id: "vehicle-016", customerId: "customer-015", make: { ar: "نيسان", en: "Nissan" }, model: { ar: "صني", en: "Sunny" }, year: 2020, plate: "خ د ذ 6677", color: { ar: "ذهبي", en: "Gold" }, fuelType: "gasoline", status: "inactive", mileage: 69300 },
  { id: "vehicle-017", customerId: "customer-016", make: { ar: "مرسيدس", en: "Mercedes-Benz" }, model: { ar: "C200", en: "C200" }, year: 2021, plate: "ر ز س 8899", color: { ar: "أسود", en: "Black" }, fuelType: "gasoline", status: "active", mileage: 41700 },
  { id: "vehicle-018", customerId: "customer-017", make: { ar: "كيا", en: "Kia" }, model: { ar: "بيكانتو", en: "Picanto" }, year: 2022, plate: "ش ص ض 1010", color: { ar: "أزرق", en: "Blue" }, fuelType: "gasoline", status: "active", mileage: 22800 },
  { id: "vehicle-019", customerId: "customer-010", make: { ar: "فورد", en: "Ford" }, model: { ar: "رينجر", en: "Ranger" }, year: 2022, plate: "ن م و 3310", color: { ar: "رمادي", en: "Gray" }, fuelType: "diesel", status: "active", mileage: 29600 },
  { id: "vehicle-020", customerId: "customer-003", make: { ar: "شفروليه", en: "Chevrolet" }, model: { ar: "تاهو", en: "Tahoe" }, year: 2016, plate: "ق ط ع 5621", color: { ar: "أبيض", en: "White" }, fuelType: "gasoline", status: "sold", mileage: 221500 },
];
