import { PrintDocument } from "@/components/patterns/print-document";
import { getDirection } from "@/i18n/routing";
import { formatAddress } from "@/lib/domain/address";
import { formatDate } from "@/lib/format";
import { companyProfile } from "@/lib/legal/company";
import { getVehicleDisplayName } from "@/modules/vehicles/display";

import type { EstimateReadModel } from "../read-models";

/**
 * عرض سعر رسمي للطباعة.
 *
 * **ليس فاتورة ولا مستندًا ضريبيًا** — لا رقم تسلسلي ضريبي ولا رمز QR،
 * والنص أسفل المستند يقول ذلك صراحةً. الخلط بينهما يعرّض المنشأة
 * لمخالفة، والعميل قد يعتبر الورقة إثبات دفع.
 *
 * النصوص هنا مكتوبة في جدول `labels` لا عبر `useTranslations`: مكوّن
 * الطباعة يعرض **اللغتين معًا** على نفس الورقة أحيانًا، وهو خارج سياق
 * لغة الواجهة — نفس نمط `invoice-print.tsx`.
 */
const labels = {
  ar: {
    title: "عرض سعر",
    quoteNo: "مرجع العرض",
    createdAt: "تاريخ العرض",
    validUntil: "صالح حتى",
    seller: "بيانات مقدّم العرض",
    customer: "بيانات العميل",
    vehicle: "المركبة",
    plate: "اللوحة",
    vatNumber: "الرقم الضريبي",
    cr: "السجل التجاري",
    address: "العنوان",
    phone: "الجوال",
    description: "الوصف",
    qty: "الكمية",
    unitPrice: "سعر الوحدة",
    lineTotal: "الإجمالي",
    total: "الإجمالي التقديري",
    currency: "ر.س",
    notes: "ملاحظات",
    disclaimer:
      "هذا عرض سعر تقديري وليس فاتورة ضريبية. الأسعار غير شاملة ضريبة القيمة المضافة ما لم يُذكر خلاف ذلك، وقد تتغيّر بعد الفحص أو بعد انتهاء مدة الصلاحية.",
    signature: "توقيع العميل بالموافقة",
    generatedBy: "مستند صادر آليًا من نظام إدارة ورشة النعماني",
  },
  en: {
    title: "Price Quotation",
    quoteNo: "Quotation Ref.",
    createdAt: "Quotation Date",
    validUntil: "Valid Until",
    seller: "Issued By",
    customer: "Customer",
    vehicle: "Vehicle",
    plate: "Plate",
    vatNumber: "VAT Number",
    cr: "CR Number",
    address: "Address",
    phone: "Phone",
    description: "Description",
    qty: "Qty",
    unitPrice: "Unit Price",
    lineTotal: "Total",
    total: "Estimated Total",
    currency: "SAR",
    notes: "Notes",
    disclaimer:
      "This is an estimated price quotation, not a tax invoice. Prices exclude VAT unless stated otherwise and may change after inspection or once the validity period ends.",
    signature: "Customer approval signature",
    generatedBy: "Document generated by Al-Numani Workshop Management System",
  },
} as const;

export function QuotePrint({
  model,
  locale,
}: {
  model: EstimateReadModel;
  locale: string;
}) {
  const lang = locale === "en" ? "en" : "ar";
  const l = labels[lang];
  const { estimate, customer, vehicle, total } = model;

  const amount = new Intl.NumberFormat(lang === "ar" ? "ar-SA" : "en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

  return (
    <PrintDocument dir={getDirection(lang)}>
      <header className="flex items-start justify-between border-b border-black/40 pb-3">
        <div>
          <h1 className="text-lg font-bold">{l.title}</h1>
          <p className="mt-1 text-[10px]">{companyProfile.tradeName[lang]}</p>
        </div>
        <dl className="text-[10px]">
          <div className="flex gap-2">
            <dt className="font-semibold">{l.quoteNo}:</dt>
            <dd dir="ltr">{estimate.number}</dd>
          </div>
          <div className="flex gap-2">
            <dt className="font-semibold">{l.createdAt}:</dt>
            <dd>{formatDate(estimate.createdAt, lang)}</dd>
          </div>
          <div className="flex gap-2">
            <dt className="font-semibold">{l.validUntil}:</dt>
            <dd>{formatDate(estimate.validUntil, lang)}</dd>
          </div>
        </dl>
      </header>

      <section className="mt-3 grid grid-cols-2 gap-4">
        <div>
          <h2 className="mb-1 text-[11px] font-bold">{l.seller}</h2>
          <p>{companyProfile.legalName[lang]}</p>
          <p dir="ltr">
            {l.vatNumber}: {companyProfile.vatNumber}
          </p>
          <p dir="ltr">
            {l.cr}: {companyProfile.commercialRegistration}
          </p>
          <p>
            {l.address}: {formatAddress(companyProfile.nationalAddress, lang)}
          </p>
        </div>
        <div>
          <h2 className="mb-1 text-[11px] font-bold">{l.customer}</h2>
          <p>{(customer.legalName ?? customer.displayName)[lang]}</p>
          {customer.phone ? (
            <p dir="ltr">
              {l.phone}: {customer.phone}
            </p>
          ) : null}
          {customer.vatNumber ? (
            <p dir="ltr">
              {l.vatNumber}: {customer.vatNumber}
            </p>
          ) : null}
          <p>
            {l.vehicle}: {getVehicleDisplayName(vehicle, lang)}
          </p>
          <p dir="ltr">
            {l.plate}: {vehicle.plate}
          </p>
        </div>
      </section>

      <table className="mt-4 w-full border-collapse text-[10px]">
        <thead>
          <tr className="border-y border-black/40">
            <th className="py-1 text-start">{l.description}</th>
            <th className="py-1 text-end">{l.qty}</th>
            <th className="py-1 text-end">{l.unitPrice}</th>
            <th className="py-1 text-end">{l.lineTotal}</th>
          </tr>
        </thead>
        <tbody>
          {estimate.items.map((item) => (
            <tr key={item.id} className="border-b border-black/15">
              <td className="py-1">{item.description[lang]}</td>
              <td className="py-1 text-end">{item.qty}</td>
              <td className="py-1 text-end">{amount.format(item.unitPrice)}</td>
              <td className="py-1 text-end">{amount.format(item.qty * item.unitPrice)}</td>
            </tr>
          ))}
        </tbody>
        <tfoot>
          <tr className="border-t border-black/40">
            <td colSpan={3} className="py-1.5 text-end font-bold">
              {l.total}
            </td>
            <td className="py-1.5 text-end font-bold">
              {amount.format(total)} {l.currency}
            </td>
          </tr>
        </tfoot>
      </table>

      {estimate.notes ? (
        <section className="mt-3">
          <h2 className="text-[11px] font-bold">{l.notes}</h2>
          <p className="text-[10px]">{estimate.notes[lang]}</p>
        </section>
      ) : null}

      <p className="mt-4 border border-black/30 p-2 text-[9px] leading-relaxed">
        {l.disclaimer}
      </p>

      <div className="mt-8 flex justify-between text-[10px]">
        <span>{l.signature}: ______________________</span>
        <span>{formatDate(new Date().toISOString(), lang)}</span>
      </div>

      <footer className="mt-6 border-t border-black/20 pt-2 text-center text-[9px]">
        {l.generatedBy}
      </footer>
    </PrintDocument>
  );
}
